app = "reversedpxy"
primary_region = "bos"

[build]
  dockerfile = "Dockerfile"

[processes]

[env]

[mounts]
  source = "valid_volume_name"
  destination = "/data"

[resources]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80